from pathlib import Path

path = Path("apps/backend/lib/arbor/agency/openaiAgent.ts")
text = path.read_text()
old = '''      if (\n        verification.complete\n      ) {\n        await input.hooks\n          ?.onComplete?.({\n            rounds: round + 1,\n            toolCalls,\n            text,\n          });\n\n        return {\n          status: "complete",\n          text,\n          responseId:\n            response.id,\n          toolCalls,\n        };\n      }\n\n      response =\n        await openai.responses.create(\n          {\n            model:\n              process.env\n                .OPENAI_AGENCY_MODEL ??\n              process.env\n                .OPENAI_MODEL ??\n              "gpt-5",\n            instructions:\n              input.instructions,\n            previous_response_id:\n              response.id,\n            input: [\n              "INTERNAL COMPLETION CHECK: the goal is not complete.",\n              `Unresolved work: ${\n                verification\n                  .unresolvedWork\n                  .join("; ") ||\n                "unspecified"\n              }`,\n              verification\n                .strategyCorrection\n                ? `Strategy correction: ${verification.strategyCorrection}`\n                : "",\n              "Continue the work now. Use available tools/research when useful.",\n              "Do not merely report what remains if it can be completed with an available reversible action.",\n            ]\n              .filter(Boolean)\n              .join("\\n"),\n            ...toolFields,\n          },\n        );'''
new = '''      const behaviorClean =\n        verification\n          .behaviorViolations\n          .length === 0;\n\n      if (\n        verification.complete &&\n        behaviorClean\n      ) {\n        await input.hooks\n          ?.onComplete?.({\n            rounds: round + 1,\n            toolCalls,\n            text,\n          });\n\n        return {\n          status: "complete",\n          text,\n          responseId:\n            response.id,\n          toolCalls,\n        };\n      }\n\n      response =\n        await openai.responses.create(\n          {\n            model:\n              process.env\n                .OPENAI_AGENCY_MODEL ??\n              process.env\n                .OPENAI_MODEL ??\n              "gpt-5",\n            instructions:\n              input.instructions,\n            previous_response_id:\n              response.id,\n            input: [\n              verification.complete\n                ? "INTERNAL BEHAVIOR CHECK: the candidate completed the goal but violated protected Arbor behavior."\n                : "INTERNAL COMPLETION CHECK: the goal is not complete.",\n              !verification.complete\n                ? `Unresolved work: ${\n                    verification\n                      .unresolvedWork\n                      .join("; ") ||\n                    "unspecified"\n                  }`\n                : "",\n              verification\n                .behaviorViolations\n                .length\n                ? `Behavior violations: ${verification.behaviorViolations.join("; ")}`\n                : "",\n              verification\n                .strategyCorrection\n                ? `Strategy correction: ${verification.strategyCorrection}`\n                : "",\n              "Continue the work now. Use available tools/research when useful.",\n              "Produce a corrected candidate that satisfies the goal without repeating any reported behavior violation.",\n              "Do not merely report what remains if it can be completed with an available reversible action.",\n            ]\n              .filter(Boolean)\n              .join("\\n"),\n            ...toolFields,\n          },\n        );'''
count = text.count(old)
if count != 1:
    raise SystemExit(f"expected one behavior-return block, found {count}")
path.write_text(text.replace(old, new, 1))
