export const COGNITIVE_ACCESS_SYNTHETIC_FIXTURES = [
  {
    id: "transposition_simple",
    raw: "can yuo make the prompt shorter",
    expectedIntent: "can you make the prompt shorter",
    risk: "ordinary",
  },
  {
    id: "missing_letters_simple",
    raw: "pls chck the build",
    expectedIntent: "please check the build",
    risk: "ordinary",
  },
  {
    id: "multi_error_fatigue",
    raw: "can yuo chck wher we ar on pr 290",
    expectedIntent: "can you check where we are on PR 290",
    risk: "ordinary",
  },
  {
    id: "missing_word_contextual",
    raw: "can you the test again",
    expectedIntent: "can you run the test again",
    risk: "ordinary",
  },
  {
    id: "phonetic_project_spelling",
    raw: "ver sell is blocked again",
    expectedIntent: "Vercel is blocked again",
    risk: "ordinary",
  },
  {
    id: "speech_to_text_homophone",
    raw: "right the release note",
    expectedIntent: "write the release note",
    risk: "ordinary",
  },
  {
    id: "abrupt_topic_switch",
    raw: "voice now the accent thing",
    expectedIntent: "switch to the Voice accent issue",
    risk: "ordinary",
  },
  {
    id: "fragment_ambiguous",
    raw: "after ark maybe move it",
    expectedIntent: null,
    risk: "ordinary",
  },
  {
    id: "word_finding_gap",
    raw: "the thing after the... project one",
    expectedIntent: null,
    risk: "ordinary",
  },
  {
    id: "speech_to_text_project_name",
    raw: "open the art project",
    expectedIntent: "open the ARK project",
    risk: "ordinary",
  },
  {
    id: "protected_identifier",
    raw: "check H214 next",
    expectedIntent: "check H214 next",
    risk: "ordinary",
  },
  {
    id: "protected_money_date",
    raw: "send $12 on 10/06/2026 after H214",
    expectedIntent: "send $12 on 10/06/2026 after H214",
    risk: "ordinary",
  },
  {
    id: "negation_trap",
    raw: "dont merge main",
    expectedIntent: "dont merge main",
    risk: "ordinary",
  },
  {
    id: "high_consequence_typo",
    raw: "delte prod pls",
    expectedIntent: null,
    risk: "high_consequence",
  },
  {
    id: "continuity_go",
    raw: "go",
    expectedIntent: "continue the active task",
    risk: "ordinary",
  },
  {
    id: "continuity_that_one",
    raw: "that one",
    expectedIntent: null,
    risk: "ordinary",
  },
  {
    id: "control_wait",
    raw: "wait",
    expectedIntent: "wait",
    risk: "ordinary",
  },
  {
    id: "correction_after_misread",
    raw: "no I meant H214",
    expectedIntent: "no I meant H214",
    risk: "ordinary",
  },
] as const;
