import {describe,expect,it} from "vitest";
import {longitudinalObservationsToPacket,type LongitudinalObservationInput} from "./longitudinalExportAdapter.js";
const obs=(partial:Partial<LongitudinalObservationInput>&Pick<LongitudinalObservationInput,"id"|"value">):LongitudinalObservationInput=>({scope:"arbor",subjectKey:"arbor",attributeKey:"continuity",polarity:1,observedAt:"2026-01-01T00:00:00Z",confidence:.9,evidence:[{sourceId:`chat:${partial.id}`,occurredAt:"2026-01-01T00:00:00Z",kind:"retrieved_record",confidence:1}],isInference:false,tags:[],...partial});
describe("longitudinal export bridge",()=>{
 it("preserves old and corrected observations as separate evidence",()=>{const p=longitudinalObservationsToPacket([obs({id:"old",value:"unreliable",correctedByObservationId:"new"}),obs({id:"new",value:"evidence-routed",observedAt:"2026-08-17T00:00:00Z",supersedesObservationId:"old"})]);expect(p.evidence).toHaveLength(2);expect(p.evidence.map(e=>(e.value as any).value)).toEqual(["unreliable","evidence-routed"]);expect(p.challenges[0]?.resolved).toBe(false);});
 it("keeps inference visibly unresolved rather than laundering it into fact",()=>{const p=longitudinalObservationsToPacket([obs({id:"inferred",value:"pattern",isInference:true,inferenceMethod:"longitudinal_pattern_discovery"})]);expect(p.unresolved).toContain("inference:inferred");expect((p.evidence[0]?.value as any).isInference).toBe(true);});
 it("flags observations with no receipt",()=>{const p=longitudinalObservationsToPacket([obs({id:"bare",value:"claim",evidence:[]})]);expect(p.unresolved).toContain("missing-evidence:bare");});
 it("retains source IDs and temporal fields",()=>{const p=longitudinalObservationsToPacket([obs({id:"dated",value:"state",observedAt:"2025-10-01T00:00:00Z",evidence:[{sourceId:"archive:old",occurredAt:"2025-10-01T00:00:00Z",kind:"retrieved_record",confidence:1}]})]);expect(p.provenance).toContain("archive:old");expect((p.evidence[0]?.value as any).observedAt).toBe("2025-10-01T00:00:00Z");});
});
