import {describe,expect,it} from "vitest";
import {assembleLongitudinalCorpus,splitFrozenExportSlices} from "./exportCorpus.js";
import {runFrozenExportComparison} from "./exportComparisonRunner.js";
import {createRealExportRuntimes} from "./realExportRuntimes.js";
import {longitudinalInvariantOracle} from "./realExportGate.js";
import type {LongitudinalObservationInput} from "./longitudinalExportAdapter.js";
const directRuns=[2,4,6,4,4,3,4,6,4,4,4,6,3,4,3,4,3,6,3,1,5,6,2,4,2,5,5,3,5,3,1,3,4,2,2,6];
function structuralObservations():LongitudinalObservationInput[]{const out:LongitudinalObservationInput[]=[];let i=0;for(const directCount of directRuns){for(let j=0;j<directCount;j++,i++)out.push({id:`o-${i}`,scope:"arbor",subjectKey:"arbor",attributeKey:"direct",value:"redacted-direct",polarity:1,observedAt:"2026-01-01T00:00:00Z",confidence:.95,evidence:[{sourceId:`source-${i}`,occurredAt:"2026-01-01T00:00:00Z",kind:"message",confidence:1}],isInference:false,tags:["structural-replay"]});out.push({id:`o-${i}`,scope:"arbor",subjectKey:"arbor",attributeKey:"synthesis",value:"redacted-inference",polarity:1,observedAt:"2026-01-01T00:00:00Z",confidence:.95,evidence:[{sourceId:`source-${i}`,occurredAt:"2026-01-01T00:00:00Z",kind:"finding",confidence:1}],isInference:true,inferenceMethod:"archaeology synthesis",tags:["structural-replay"]});i++;}return out;}
function slices(){const observations=structuralObservations();expect(observations).toHaveLength(172);expect(observations.filter(o=>o.isInference)).toHaveLength(36);const corpus=assembleLongitudinalCorpus([observations],1);const result=splitFrozenExportSlices(corpus.packets,.2,"real-export:A","real-export:B");expect(result.development.packets).toHaveLength(135);expect(result.heldOut.packets).toHaveLength(37);return result;}
async function compare(slice:ReturnType<typeof slices>["development"]){const {candidate,baseline}=createRealExportRuntimes();return runFrozenExportComparison({slice,candidate,baseline,oracle:longitudinalInvariantOracle,kind:"real-export"});}
describe("real export structural replay",()=>{
 it("development A remains green",async()=>{const report=await compare(slices().development);expect(report.comparison.candidate.accuracy).toBe(1);expect(report.comparison.baseline.accuracy).toBe(1);expect(report.comparison.candidate.falseReleaseRate).toBe(0);expect(report.candidateProvenanceRetention).toBe(1);expect(report.comparison.candidate.meanCompute).toBeCloseTo(1+29/135,10);expect(report.comparison.candidate.assertRate).toBeCloseTo(106/135,10);});
 it("executes the frozen held-out B gate",async()=>{const report=await compare(slices().heldOut);expect(report.comparison.candidate.accuracy).toBe(1);expect(report.comparison.baseline.accuracy).toBe(1);expect(report.comparison.candidate.falseReleaseRate).toBe(0);expect(report.comparison.baseline.falseReleaseRate).toBe(0);expect(report.candidateProvenanceRetention).toBe(1);expect(report.baselineProvenanceRetention).toBe(1);expect(report.comparison.candidate.meanCompute).toBeCloseTo(1+7/37,10);expect(report.comparison.baseline.meanCompute).toBe(1);expect(report.comparison.candidate.assertRate).toBeCloseTo(30/37,10);expect(report.comparison.baseline.assertRate).toBeCloseTo(30/37,10);});
});
