import { describe, expect, it } from "vitest";
import { AdaptiveComputePolicy } from "./adaptiveCompute.js";
import { CogMoleculeRuntime } from "./runtime.js";
import type { Cog, CogPacket } from "./types.js";
const packet = (): CogPacket => ({ id: "p1", evidence: [], hypotheses: [], unresolved: ["late evidence"], challenges: [], provenance: ["test"], friction: 999, circulation: 0, metadata: {} });
const projection = async (current: CogPacket, reasons: string[]) => ({ disposition: "assert" as const, packet: current, ordered: ["resolved"], provenance: current.provenance, confidence: 0.99, friction: current.friction, reasons });
describe("CogMoleculeRuntime", () => {
  it("keeps unresolved information live until later circulation resolves it", async () => { const cog: Cog = { id: "resolver", async process(current, context) { const next = structuredClone(current); if (context.round >= 2) next.unresolved = []; return { packet: next, reasons: [context.round >= 2 ? "resolved" : "still live"] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], releaseFriction: 0.05, validate: async () => ({ valid: true, reasons: ["validated"] }), project: projection }); const result = await runtime.run(packet()); expect(result.disposition).toBe("assert"); expect(result.packet.unresolved).toEqual([]); expect(result.rounds).toBeGreaterThanOrEqual(3); expect(result.computeSpent).toBe(result.rounds); });
  it("dedupes exact repeated observations so recurrence can converge", async () => { const cog: Cog = { id: "reobserver", async process(current, context) { const next = structuredClone(current); if (context.round >= 2) { next.evidence.push({ id: "late-source", value: "same observation", provenance: ["source:late"], confidence: 0.95 }); next.unresolved = []; } return { packet: next, reasons: ["observed"] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], maxRounds: 8, validate: async () => ({ valid: true, reasons: ["validated"] }), project: projection }); const result = await runtime.run(packet()); expect(result.disposition).toBe("assert"); expect(result.packet.evidence.filter((evidence) => evidence.id === "late-source")).toHaveLength(1); expect(result.rounds).toBeLessThan(8); });
  it("does not erase conflicting observations merely because they share an evidence id", async () => { const initial = packet(); initial.unresolved = []; initial.evidence = [{ id: "document:7", value: "version A", provenance: ["source:a"], confidence: 0.9 }, { id: "document:7", value: "version B", provenance: ["source:b"], confidence: 0.9 }]; const cog: Cog = { id: "quiet", async process(current) { return { packet: structuredClone(current), reasons: ["preserve evidence"] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], maxRounds: 3, validate: async (current) => ({ valid: current.evidence.length === 2, reasons: [] }), project: projection }); const result = await runtime.run(initial); expect(result.disposition).toBe("assert"); expect(result.packet.evidence).toHaveLength(2); expect(result.packet.evidence.map((evidence) => evidence.value)).toEqual(["version A", "version B"]); });
  it("recognizes semantic convergence when equivalent evidence and provenance are reordered", async () => { const initial = packet(); initial.unresolved = []; const cog: Cog = { id: "reorderer", async process(current, context) { const next = structuredClone(current); next.evidence = context.round % 2 ? [{ id: "b", value: 2, provenance: ["p2", "p1"], confidence: 0.9 }, { id: "a", value: 1, provenance: ["p1"], confidence: 0.9 }] : [{ id: "a", value: 1, provenance: ["p1"], confidence: 0.9 }, { id: "b", value: 2, provenance: ["p1", "p2"], confidence: 0.9 }]; next.provenance = context.round % 2 ? ["p2", "p1"] : ["p1", "p2"]; return { packet: next, reasons: ["same facts, different order"] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], maxRounds: 6, validate: async () => ({ valid: true, reasons: ["validated"] }), project: projection }); const result = await runtime.run(initial); expect(result.disposition).toBe("assert"); expect(result.rounds).toBeLessThan(6); });
  it("derives friction from unresolved state instead of trusting a cog supplied scalar", async () => { const cog: Cog = { id: "liar", async process(current) { return { packet: { ...current, friction: 0 }, reasons: ["claims zero friction"] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], maxRounds: 2, validate: async () => ({ valid: true, reasons: [] }), project: async () => { throw new Error("must_not_release"); } }); const result = await runtime.run(packet()); expect(result.disposition).toBe("circulate"); expect(result.packet.friction).toBeGreaterThan(0); });
  it("escalates compute when friction appears after processing begins", async () => { const cog: Cog = { id: "discover-conflict", async process(current, context) { const next = structuredClone(current); if (context.round === 1) next.hypotheses = [{ id: "h1", value: "candidate", confidence: 0, support: [], contradictions: ["c1", "c2", "c3", "c4", "c5"] }]; return { packet: next, reasons: ["processed"] }; } }; const initial = packet(); initial.unresolved = []; const runtime = new CogMoleculeRuntime({ cogs: [cog], maxRounds: 16, adaptiveCompute: new AdaptiveComputePolicy([{ maxRounds: 2, frictionAtLeast: 0 }, { maxRounds: 8, frictionAtLeast: 0.4 }]), validate: async () => ({ valid: false, reasons: [] }), project: async () => { throw new Error("must_not_release"); } }); const result = await runtime.run(initial); expect(result.rounds).toBe(8); expect(result.reasons.some((reason) => reason.startsWith("adaptive_compute_escalated:"))).toBe(true); });
  it("does not confuse convergence with validity and reopens a concrete challenge", async () => { const cog: Cog = { id: "stable-wrong", async process(current) { return { packet: { ...current, unresolved: [] }, reasons: ["stable"] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], maxRounds: 3, validate: async () => ({ valid: false, reasons: ["constraint violated"] }), project: async () => { throw new Error("must_not_release"); } }); const result = await runtime.run(packet()); expect(result.disposition).toBe("circulate"); expect(result.reasons).toContain("constraint violated"); expect(result.packet.challenges.some((challenge) => !challenge.resolved)).toBe(true); expect(result.packet.friction).toBeGreaterThan(0); });
  it("seeks instead of asserting when validation identifies missing information", async () => { const cog: Cog = { id: "quiet", async process(current) { return { packet: { ...current, unresolved: [] }, reasons: [] }; } }; const runtime = new CogMoleculeRuntime({ cogs: [cog], validate: async () => ({ valid: false, reasons: ["external evidence required"], seek: ["source document"] }), project: async () => { throw new Error("must_not_release"); } }); const result = await runtime.run(packet()); expect(result.disposition).toBe("seek_more_information"); expect(result.packet.unresolved).toContain("source document"); expect(result.packet.friction).toBeGreaterThan(0); });
});
