import { describe, expect, it } from "vitest";
import { AdaptiveComputePolicy } from "./adaptiveCompute.js";
import { CogMoleculeRuntime } from "./runtime.js";
import type { Cog, CogPacket } from "./types.js";
const p=(id:string):CogPacket=>({id,evidence:[],hypotheses:[],unresolved:[],challenges:[],provenance:["torture"],friction:0,circulation:0,metadata:{}});
const project=async(packet:CogPacket,reasons:string[])=>({disposition:"assert" as const,packet,ordered:packet.evidence.map(e=>e.id),provenance:[...new Set(packet.evidence.flatMap(e=>e.provenance))],confidence:.8,friction:packet.friction,reasons});
describe("second-stage torture matrix",()=>{
 it("handles reordered arrival",async()=>{const cog:Cog={id:"reorder",async process(cur,ctx){const n=structuredClone(cur);if(ctx.round===1)n.evidence.push({id:"4",value:4,provenance:["s4"],confidence:.9},{id:"2",value:2,provenance:["s2"],confidence:.9});if(ctx.round===2)n.evidence.push({id:"5",value:5,provenance:["s5"],confidence:.9},{id:"1",value:1,provenance:["s1"],confidence:.9},{id:"3",value:3,provenance:["s3"],confidence:.9});if(n.evidence.length>=5)n.unresolved=[];return{packet:n,reasons:["arrival"]}}};const x=p("reorder");x.unresolved=["complete"];const r=new CogMoleculeRuntime({cogs:[cog],maxRounds:8,validate:async q=>({valid:q.evidence.length===5,reasons:[]}),project:async(q,reasons)=>({...await project(q,reasons),ordered:q.evidence.map(e=>Number(e.value)).sort((a,b)=>a-b)})});const out=await r.run(x);expect(out.disposition).toBe("assert");expect(out.projection?.ordered).toEqual([1,2,3,4,5]);});
 it("repairs multiple contradictions independently",async()=>{const cog:Cog={id:"repair",async process(cur,ctx){const n=structuredClone(cur);if(ctx.round===2)n.challenges=n.challenges.map((c,i)=>i===0?{...c,resolved:true}:c);if(ctx.round>=3)n.challenges=n.challenges.map(c=>({...c,resolved:true}));return{packet:n,reasons:["repair"]}}};const x=p("multi");x.challenges=[1,2,3].map(i=>({id:`c${i}`,source:`s${i}`,target:"claim",reason:"conflict",provenance:[`s${i}`],resolved:false}));const out=await new CogMoleculeRuntime({cogs:[cog],maxRounds:8,validate:async q=>({valid:q.challenges.every(c=>c.resolved),reasons:[]}),project}).run(x);expect(out.disposition).toBe("assert");expect(out.packet.challenges.every(c=>c.resolved)).toBe(true);});
 it("seeks rather than laundering missing provenance",async()=>{const cog:Cog={id:"check",async process(cur){return{packet:structuredClone(cur),reasons:["checked"]}}};const x=p("prov");x.evidence.push({id:"claim",value:"untraceable",provenance:[],confidence:.99});const out=await new CogMoleculeRuntime({cogs:[cog],validate:async q=>q.evidence.some(e=>!e.provenance.length)?{valid:false,reasons:["missing provenance"],seek:["source-for:claim"]}:{valid:true,reasons:[]},project}).run(x);expect(out.disposition).toBe("seek_more_information");});
 it("rejects association-to-culpability inflation",async()=>{const cog:Cog={id:"qualify",async process(cur,ctx){const n=structuredClone(cur);if(ctx.round>=2)n.hypotheses=[{id:"qualified",value:"documented association only",confidence:.9,support:["contact"],contradictions:[]}];return{packet:n,reasons:["qualified"]}}};const x=p("association");x.evidence.push({id:"contact",value:"contact",provenance:["record"],confidence:.95});x.hypotheses.push({id:"inflated",value:"culpability",confidence:.8,support:["contact"],contradictions:["unsupported"]});const out=await new CogMoleculeRuntime({cogs:[cog],maxRounds:8,validate:async q=>({valid:!q.hypotheses.some(h=>String(h.value).includes("culpability")),reasons:[]}),project}).run(x);expect(out.disposition).toBe("assert");expect(out.packet.hypotheses[0]?.value).toBe("documented association only");});
 it("selectively escalates compute after late conflict",async()=>{const cog:Cog={id:"pressure",async process(cur,ctx){const n=structuredClone(cur);if(ctx.round===1&&n.metadata.hard)n.challenges.push({id:"late",source:"a",target:"b",reason:"conflict",provenance:["a","b"],resolved:false});if(ctx.round>=4)n.challenges=n.challenges.map(c=>({...c,resolved:true}));return{packet:n,reasons:["pressure"]}}};const policy=new AdaptiveComputePolicy([{maxRounds:2,frictionAtLeast:0},{maxRounds:8,frictionAtLeast:.1}]);const easy=p("easy"),hard=p("hard");hard.metadata.hard=true;const make=()=>new CogMoleculeRuntime({cogs:[cog],maxRounds:8,adaptiveCompute:policy,validate:async q=>({valid:q.challenges.every(c=>c.resolved),reasons:[]}),project});const a=await make().run(easy),b=await make().run(hard);expect(a.rounds).toBeLessThan(b.rounds);expect(b.reasons.some(r=>r.startsWith("adaptive_compute_escalated:"))).toBe(true);expect(b.disposition).toBe("assert");});
 it("dedupes repeated noise but preserves conflict",async()=>{const cog:Cog={id:"noise",async process(cur,ctx){const n=structuredClone(cur);n.evidence.push({id:"same",value:"A",provenance:["s1"],confidence:.9});if(ctx.round>=2)n.evidence.push({id:"same",value:"B",provenance:["s2"],confidence:.9});if(ctx.round>=3)n.unresolved=[];return{packet:n,reasons:["retrieved"]}}};const x=p("noise");x.unresolved=["wait"];const out=await new CogMoleculeRuntime({cogs:[cog],maxRounds:8,validate:async()=>({valid:true,reasons:[]}),project}).run(x);expect(out.disposition).toBe("assert");expect(out.packet.evidence.filter(e=>e.id==="same")).toHaveLength(2);expect(out.rounds).toBeLessThan(8);});
});
