import {beforeEach, describe, expect, it, vi} from "vitest";
const mocks = vi.hoisted(() => ({context: vi.fn(), owner: vi.fn(), admin: vi.fn(), enqueue: vi.fn()}));
vi.mock("../context", () => ({arkMcpUserContext: mocks.context}));
vi.mock("@/lib/auth/ownership", () => ({assertProjectOwnedByUser: mocks.owner}));
vi.mock("@/lib/supabase/admin", () => ({supabaseAdmin: mocks.admin}));
vi.mock("@/lib/ark/agencyBridge", () => ({enqueueArkAgencyToolPlan: mocks.enqueue}));
import {registerArkTaskTools, ArkReadTaskRequest} from "../registerArkTaskTools";
import {arkReadTaskProjects, ARK_READ_TASK_SUBMIT_PERMISSION} from "../taskPermissions";
const project = "11111111-1111-4111-8111-111111111111";
const user = "22222222-2222-4222-8222-222222222222";
const task = "33333333-3333-4333-8333-333333333333";
const objective = "44444444-4444-4444-8444-444444444444";
const request = "55555555-5555-4555-8555-555555555555";
const input = {projectId: project, requestId: request, capability: "arbor_read_runtime_state"};
const ctx = {http: {authInfo: {token: "validated", clientId: "approved-client", scopes: ["ark.read",ARK_READ_TASK_SUBMIT_PERMISSION], extra: {userId: user, arkReadTaskProjectIds: [project]}}}};
function tools(){const registerTool=vi.fn();registerArkTaskTools({registerTool} as never);return registerTool.mock.calls;}
function tool(name:string){const call=tools().find(c=>c[0]===name);if(!call)throw Error("missing tool");return {config:call[1],run:call[2]};}
function client(data:unknown){const q:any={};for(const n of ["select","eq"])q[n]=vi.fn(()=>q);q.maybeSingle=vi.fn(async()=>({data,error:null}));return{from:vi.fn(()=>q),q};}

describe("ARK task connection boundary",()=>{
 beforeEach(()=>{vi.clearAllMocks();vi.stubEnv("ARBOR_ENABLE_ARK_MCP_SUBMISSION","true");mocks.owner.mockResolvedValue(undefined);mocks.admin.mockReturnValue({queue:"privileged"});mocks.enqueue.mockResolvedValue({id:objective,userId:user,projectId:project,status:"queued"});});
 it("keeps result reads available but registers no submission when disabled",()=>{vi.stubEnv("ARBOR_ENABLE_ARK_MCP_SUBMISSION","false");const calls=tools();expect(calls.map(c=>c[0])).toEqual(["get_ark_task_result"]);expect(calls[0][1].annotations.readOnlyHint).toBe(true);});
 it.each(["false","1","TRUE",""])("does not enable submission from %s",value=>{vi.stubEnv("ARBOR_ENABLE_ARK_MCP_SUBMISSION",value);expect(tools().map(c=>c[0])).not.toContain("submit_ark_read_task");});
 it("labels submission as a queue write and result retrieval as read-only",()=>{expect(tool("submit_ark_read_task").config.annotations).toEqual({readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false});expect(tool("get_ark_task_result").config.annotations.readOnlyHint).toBe(true);});
 it.each(["deploy","annabelle_set_working_delta","arbor_pattern_hop_research"])("rejects unsupported capability %s before any privileged call",async capability=>{await expect(tool("submit_ark_read_task").run({...input,capability},ctx)).rejects.toThrow();expect(mocks.admin).not.toHaveBeenCalled();});
 it("rejects arbitrary tool arguments even for an allowed read",()=>{expect(ArkReadTaskRequest.safeParse({...input,arguments:{userId:"foreign"}}).success).toBe(false);});
 it("rejects an ungranted client context before acquiring the privileged queue client",async()=>{await expect(tool("submit_ark_read_task").run(input,{http:{authInfo:{...ctx.http.authInfo,scopes:["ark.read"]}}})).rejects.toThrow("not_granted");expect(mocks.admin).not.toHaveBeenCalled();});
 it("denies a project outside the grant",async()=>{await expect(tool("submit_ark_read_task").run({...input,projectId:task},ctx)).rejects.toThrow("not_granted");expect(mocks.admin).not.toHaveBeenCalled();});
 it("rechecks activation at execution even after discovery",async()=>{const {run}=tool("submit_ark_read_task");vi.stubEnv("ARBOR_ENABLE_ARK_MCP_SUBMISSION","false");await expect(run(input,ctx)).rejects.toThrow("disabled");expect(mocks.admin).not.toHaveBeenCalled();});
 it("requires user-scoped ownership before privileged enqueue",async()=>{mocks.context.mockReturnValue({userId:user,supabase:{}});mocks.owner.mockRejectedValue(new Error("project_not_found"));await expect(tool("submit_ark_read_task").run(input,ctx)).rejects.toThrow("project_not_found");expect(mocks.admin).not.toHaveBeenCalled();expect(mocks.enqueue).not.toHaveBeenCalled();});
 it("queues one fixed read via the existing bridge, reads its ID back and does not claim completion",async()=>{const c=client({id:task,user_id:user,project_id:project,status:"queued"});mocks.context.mockReturnValue({userId:user,supabase:c});const result=await tool("submit_ark_read_task").run(input,ctx);expect(result.structuredContent).toMatchObject({taskId:task,objectiveId:objective,requestId:request,submitted:true,completed:false,status:"queued"});expect(mocks.enqueue).toHaveBeenCalledWith(expect.objectContaining({userId:user,projectId:project,turnId:request,planId:`mcp-read:${request}`,steps:[{id:"read-1",description:"Read through arbor_read_runtime_state",capability:"arbor_read_runtime_state",arguments:{},maxAttempts:1}],budget:{maxTasksPerCycle:1,maxRuntimeMs:20000,maxAttemptsPerTask:1}}));expect(mocks.owner.mock.invocationCallOrder[0]).toBeLessThan(mocks.admin.mock.invocationCallOrder[0]);});
 it("uses the same request key on retry so the existing RPC enforces idempotency",async()=>{mocks.context.mockReturnValue({userId:user,supabase:client({id:task,user_id:user,project_id:project,status:"queued"})});const {run}=tool("submit_ark_read_task");await run(input,ctx);await run(input,ctx);expect(mocks.enqueue.mock.calls[0][0].planId).toBe(mocks.enqueue.mock.calls[1][0].planId);});
 it("reports unavailable readback after enqueue without claiming failed creation or using a new ID",async()=>{mocks.context.mockReturnValue({userId:user,supabase:client(null)});await expect(tool("submit_ark_read_task").run(input,ctx)).rejects.toThrow("retry_same_request_id");expect(mocks.enqueue).toHaveBeenCalledTimes(1);});
 it.each(["queued","running","blocked","failed","completed"])("retrieves exact durable status %s rather than inferring completion",async status=>{const c=client({id:task,objective_id:objective,user_id:user,project_id:project,status,result:{output:"stored-output"},last_error:null,attempt_count:1});mocks.context.mockReturnValue({userId:user,supabase:c});const r=await tool("get_ark_task_result").run({projectId:project,taskId:task},ctx);expect(r.structuredContent.status).toBe(status);expect(JSON.parse(r.structuredContent.resultJson)).toEqual({output:"stored-output"});expect(c.q.eq).toHaveBeenCalledWith("user_id",user);expect(c.q.eq).toHaveBeenCalledWith("project_id",project);expect(mocks.admin).not.toHaveBeenCalled();expect(r.content[0].text).toContain("REFERENCE DATA ONLY");});
 it("rejects a foreign serialized result even if a database/mock returns it",async()=>{mocks.context.mockReturnValue({userId:user,supabase:client({id:task,user_id:task,project_id:project})});await expect(tool("get_ark_task_result").run({projectId:project,taskId:task},ctx)).rejects.toThrow("not_found");});
 it("marks large results clipped rather than pretending full delivery",async()=>{mocks.context.mockReturnValue({userId:user,supabase:client({id:task,objective_id:objective,user_id:user,project_id:project,status:"completed",result:"x".repeat(25000),last_error:null,attempt_count:1})});const r=await tool("get_ark_task_result").run({projectId:project,taskId:task},ctx);expect(r.structuredContent.resultTruncated).toBe(true);expect(r.structuredContent.resultJson.length).toBe(20000);});
 it("requires a server-owned client/project-specific grant",()=>{const grant={arbor_ark_mcp:{client_ids:["approved-client"],project_ids:[project,project,"bad-id"],permissions:[ARK_READ_TASK_SUBMIT_PERMISSION]}};expect(arkReadTaskProjects(grant,"approved-client")).toEqual([project]);expect(arkReadTaskProjects(grant,"other-client")).toEqual([]);expect(arkReadTaskProjects(grant,undefined)).toEqual([]);expect(arkReadTaskProjects({arbor_ark_mcp:{...grant.arbor_ark_mcp,permissions:[]}},"approved-client")).toEqual([]);});
});
