import type { SupabaseClient } from "@supabase/supabase-js";
import { openAIEmbed } from "@/lib/providers/openai";

export type RetrievedMemoryItem = { id:string; project_id:string|null; conversation_id:string|null; key:string; value:Record<string,any>; tier:"core"|"normal"|"sensitive"; scope:"global"|"project"|"conversation"; user_trigger_only:boolean; importance:number; confidence:number; mention_count:number; correction_count:number; pinned:boolean; locked:boolean; status:string; deleted_at:string|null; last_seen_at:string|null; last_reinforced_at:string|null; updated_at:string|null; similarity?:number; content_text:string; };
export type MemoryContextResult = { core:RetrievedMemoryItem[]; normal:RetrievedMemoryItem[]; sensitive:RetrievedMemoryItem[]; keysUsed:string[]; };
function toPlainObject(value:any):Record<string,any>{ if(value&&typeof value==="object"&&!Array.isArray(value))return value; if(typeof value==="string")return{text:value}; return{}; }
function contentTextForRow(row:{key?:string|null;value?:any}){const value=toPlainObject(row.value);const explicit=typeof value.text==="string"?value.text.trim():typeof value.value==="string"?value.value.trim():"";if(explicit)return explicit;return `${row.key??"memory"}: ${Object.keys(value).length?JSON.stringify(value):"{}"}`;}
function normalizeRow(row:any):RetrievedMemoryItem{return{id:String(row.id),project_id:row.project_id?String(row.project_id):null,conversation_id:row.conversation_id?String(row.conversation_id):null,key:String(row.key??"").trim(),value:toPlainObject(row.value),tier:(row.tier??(row.pinned?"core":"normal")) as RetrievedMemoryItem["tier"],scope:(row.scope??"conversation") as RetrievedMemoryItem["scope"],user_trigger_only:!!row.user_trigger_only,importance:Number(row.importance??5),confidence:Number(row.confidence??.75),mention_count:Number(row.mention_count??0),correction_count:Number(row.correction_count??0),pinned:!!row.pinned,locked:!!row.locked,status:String(row.status??"active"),deleted_at:row.deleted_at??null,last_seen_at:row.last_seen_at??null,last_reinforced_at:row.last_reinforced_at??null,updated_at:row.updated_at??null,similarity:typeof row.similarity==="number"?row.similarity:undefined,content_text:contentTextForRow(row)};}
function isLiveRow(row:any){return row&&row.status==="active"&&row.deleted_at==null;}
export function isMemoryInProjectScope(item:Pick<RetrievedMemoryItem,"project_id"|"scope">&Partial<Pick<RetrievedMemoryItem,"conversation_id">>,projectId:string|null,conversationId:string|null=null){if(item.scope==="global")return true;if(item.scope==="project")return projectId?item.project_id===projectId:item.project_id==null;if(item.scope==="conversation")return Boolean(projectId&&conversationId&&item.project_id===projectId&&item.conversation_id===conversationId);return false;}
function hoursSince(value:string|null|undefined){if(!value)return Number.POSITIVE_INFINITY;const time=Date.parse(value);return Number.isFinite(time)?(Date.now()-time)/3_600_000:Number.POSITIVE_INFINITY;}
function clamp01(value:number){return Math.max(0,Math.min(1,value));}
export function memoryStabilityScore(item:RetrievedMemoryItem){const similarity=clamp01(item.similarity??0),importance=clamp01((item.importance-1)/9),reinforcement=clamp01(Math.log1p(Math.max(0,item.mention_count??0))/Math.log(11)),correctionAuthority=clamp01(Math.max(0,item.correction_count??0)/3),hours=Math.min(hoursSince(item.last_reinforced_at??item.last_seen_at??item.updated_at),24*30),recency=Number.isFinite(hours)?Math.exp(-hours/(24*7)):0;return similarity*.5+importance*.18+reinforcement*.12+correctionAuthority*.1+recency*.1+(item.pinned?.2:0)+(item.locked?.1:0);}
async function enrichMemoryStrength(supabase:SupabaseClient,items:RetrievedMemoryItem[]){if(!items.length)return items;const ids=Array.from(new Set(items.map(i=>i.id).filter(Boolean)));const{data,error}=await supabase.from("memory_items").select("id,mention_count,correction_count").in("id",ids);if(error){console.warn("[memory:retrieval] strength enrichment failed",{subsystem:"memory",operation:"strength_enrichment"});return items;}const byId=new Map((data??[]).map((row:any)=>[String(row.id),{mention_count:Number(row.mention_count??0),correction_count:Number(row.correction_count??0)}]));return items.map(item=>({...item,...(byId.get(item.id)??{})}));}
function applyScope(query:any,projectId:string|null,conversationId:string|null){if(projectId){const scoped=["scope.eq.global",`and(scope.eq.project,project_id.eq.${projectId})`,conversationId?`and(scope.eq.conversation,project_id.eq.${projectId},conversation_id.eq.${conversationId})`:null].filter(Boolean).join(",");return query.or(scoped);}return query.eq("scope","global");}
export async function getAlwaysIncludedMemoryAnchors(input:{supabase:SupabaseClient;authedUserId:string;projectId:string|null;conversationId:string|null;limit?:number;}):Promise<RetrievedMemoryItem[]>{let query=input.supabase.from("memory_items").select("id, user_id, project_id, conversation_id, key, value, tier, scope, user_trigger_only, importance, confidence, mention_count, correction_count, locked, pinned, status, deleted_at, last_seen_at, last_reinforced_at, updated_at").eq("user_id",input.authedUserId).eq("status","active").is("deleted_at",null).or("tier.eq.core,pinned.eq.true,locked.eq.true");query=applyScope(query,input.projectId,input.conversationId);const{data,error}=await query.order("importance",{ascending:false}).order("updated_at",{ascending:false}).limit(Math.max(1,Math.min(input.limit??24,60)));if(error)throw error;return(data??[]).filter(isLiveRow).map(normalizeRow).filter((item:RetrievedMemoryItem)=>isMemoryInProjectScope(item,input.projectId,input.conversationId));}
async function directMemoryFallback(input:{supabase:SupabaseClient;authedUserId:string;projectId:string|null;conversationId:string|null;}):Promise<RetrievedMemoryItem[]>{let query=input.supabase.from("memory_items").select("id, user_id, project_id, conversation_id, key, value, tier, scope, user_trigger_only, importance, confidence, mention_count, correction_count, locked, pinned, status, deleted_at, last_seen_at, last_reinforced_at, updated_at").eq("user_id",input.authedUserId).is("deleted_at",null).eq("status","active").order("pinned",{ascending:false}).order("importance",{ascending:false}).order("last_reinforced_at",{ascending:false}).limit(50);query=applyScope(query,input.projectId,input.conversationId);const{data,error}=await query;if(error)throw error;return(data??[]).filter(isLiveRow).map(normalizeRow).filter((item:RetrievedMemoryItem)=>isMemoryInProjectScope(item,input.projectId,input.conversationId));}
export async function getMemoryContext(params:{supabase:SupabaseClient;authedUserId:string;projectId?:string|null;conversationId?:string|null;latestUserText:string;useVectorSearch?:boolean;useCache?:boolean;}){const{supabase,authedUserId,projectId=null,conversationId=null,latestUserText,useVectorSearch=false}=params;void params.useCache;let items:RetrievedMemoryItem[]=[];if(useVectorSearch&&projectId&&latestUserText.trim().length>=3){try{const queryEmbedding=await openAIEmbed(latestUserText.trim());const{data,error}=await supabase.rpc("match_memories_v3",{p_user_id:authedUserId,p_project_id:projectId,p_conversation_id:conversationId,p_query_embedding:queryEmbedding,p_match_count:40});if(error)throw error;items=(data??[]).filter(isLiveRow).map(normalizeRow).filter((item:RetrievedMemoryItem)=>isMemoryInProjectScope(item,projectId,conversationId));items=await enrichMemoryStrength(supabase,items);items=items.sort((a,b)=>memoryStabilityScore(b)-memoryStabilityScore(a)).slice(0,30);}catch{console.warn("[memory:retrieval] vector fallback",{subsystem:"memory",operation:"vector_fallback"});items=await directMemoryFallback({supabase,authedUserId,projectId,conversationId});}}else items=await directMemoryFallback({supabase,authedUserId,projectId,conversationId});return{core:items.filter(i=>i.tier==="core"||i.pinned),normal:items.filter(i=>i.tier==="normal"&&!i.user_trigger_only&&!i.pinned),sensitive:items.filter(i=>i.tier==="sensitive"||i.user_trigger_only),keysUsed:items.map(i=>i.key).filter(Boolean)} as MemoryContextResult;}
